services:
  db:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: winwin-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1314"
      POSTGRES_DB: winwin_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d winwin_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-api:
    build:
      context: ./auth-api
    platform: linux/amd64
    container_name: auth-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/winwin_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1314
      - JWT_SECRET=eating_beating_screamin_jumping_helloworld
      - JWT_EXPIRATION=86400000
      - INTERNAL_TOKEN=winwin-internal-secret-token-123
      - SERVICE_B_URL=http://data-api:8081

  data-api:
    build:
      context: ./data-api
    platform: linux/amd64
    container_name: data-api
    ports:
      - "8081:8081"
    environment:
      - INTERNAL_TOKEN=winwin-internal-secret-token-123